extends GdUnitTestSuite

## CONTRACT for the Score type (Phase 8 acceptance test of the dev loop).
## Executor task: implement res://src/score.gd so every test below passes.
## Run `./scripts/test.sh` until green. Do not edit this file.

func test_new_score_starts_at_zero() -> void:
	var score := Score.new()
	assert_int(score.value).is_equal(0)

func test_add_increases_value() -> void:
	var score := Score.new()
	score.add(30)
	assert_int(score.value).is_equal(30)

func test_add_accumulates() -> void:
	var score := Score.new()
	score.add(30)
	score.add(25)
	assert_int(score.value).is_equal(55)

func test_add_clamps_at_100() -> void:
	var score := Score.new()
	score.add(150)
	assert_int(score.value).is_equal(100)

func test_add_clamps_at_100_after_accumulation() -> void:
	var score := Score.new()
	score.add(80)
	score.add(50)
	assert_int(score.value).is_equal(100)

## Pin the memory model: a Score is a value object, so it must be RefCounted
## (auto-freed). extends Object/Node leaks at exit; this test forbids that.
func test_score_is_refcounted() -> void:
	assert_bool(Score.new() is RefCounted).is_true()
